combine = {("LGA", "JFK", "EWA", "HPN", "ISP"): "LGA",
("IAD", "DCA"): "IAD",
("MIA", "FLL", "PBI"): "MIA",
("OAK", "SFO" ): "OAK",
("ORD", "MDW"): "ORD",
("DAL", "DFW"): "DAL",
("HOU", "IAH" ): "HOU",
("LAX", "SNA", "BUR", "ONT"): "LAX",
("MCO", "SFB"): "MCO",
("PHX", "AZA" ): "PHX",
("PIE", "TPA"): "PIE",
("PWM", "PDX"): "PWM",
("CAK", "CLE"): "CAK",
("ANI", "BET"): "ANI",
("UNK", "OME"): "UNK"}
routeList = ["LGA", "JFK", "EWA", "HPN", "ISP", "IAD", "DCA", "MIA", "FLL", "PBI", "OAK", "SFO" ,"ORD", "MDW", "DAL", "DFW", "HOU", "IAH" ,"LAX", "SNA", "BUR", "ONT", "MCO", "SFB", "PHX", "AZA" ,"PIE", "TPA", "PWM", "PDX", "CAK", "CLE", "ANI", "BET", "UNK", "OME"]
